### ISSUE TITLE
Optimized Manifest Schema

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/monorepo#46]
**Option 1:**
```yaml
api:
  schema:
    file: ./src/schema.graphql
  mutation:
    language: wasm/assemblyscript
    file: ./src/mutation/index.ts
  query:
    language: wasm/assemblyscript
    file: ./src/query/index.ts
```

**Option 2:**
```yaml
api:
  schemas:
    - file: ./src/mutation/schema.graphql
    - file: ./src/query/schema.graphql
  mutation:
    language: wasm/assemblyscript
    file: ./src/mutation/index.ts
  query:
    language: wasm/assemblyscript
    file: ./src/query/index.ts
```
